### ISSUE TITLE
Get branch commits

### ISSUE THREAD

**Issue by dshmelev** [hirakiuc/tinybucket#112]
Hi!
How can I get all branch commits?
I want to do it like this
```
bb = Tinybucket.new
bb.repo('Org', 'Repo').commits(branch: 'master')
```

Thanks

**Comment by dshmelev** [comment]
Close issue. Answer below
```
bb.repo('Org', 'Repo').branch('master').commits
```

**Comment by hirakiuc** [comment]
Hi, @dshmelev  😄 

I'm sorry that I found your issue just now 🙇 

Your answer is right if you want to fetch commits in the master branch 👍 
(NOTE: currently, `branch feature` is not released yet. I'll release in next release 1.4.0!) 

But, if you want to fetch all commits in the repository, you should try below code.

```
bb.repo('Org', 'Repo').commits
```

=> [yard docs](http://www.rubydoc.info/github/hirakiuc/tinybucket/master/Tinybucket/Model/Repository#commits-instance_method)

Sorry for my poor documentations 😭 

I hope that you enjoy my gem 😄
