### ISSUE TITLE
can't get this to work with oauth

### ISSUE THREAD

**Issue by kevinchugh** [hirakiuc/tinybucket#44]
I have successfully authenticated to BB with oauth.  I have 4 hashes:

- consumer secret
- consumer key
- oauth token
- oauth token secret

You  use the vocabulary:

config.oauth_key    = 'key'
config.oauth_secret = 'secret'

are these the consumer key and consumer secret?  If so, how do you use the access token?  I've tried every combo, I get a 401 every time.  

Thanks for any help,
kevin

**Comment by kevinchugh** [comment]
Examining your code, I believe you have a typo in your Readme, didn't have rights to issue a PR, but please change

bucket = Tinybucket.new do |config|
  config.oauth_key    = 'key'
  config.oauth_secret = 'secret'
end

to

bucket = Tinybucket.new do |config|
  config.oauth_token    = 'key'           #<------------ change this line please
  config.oauth_secret = 'secret'
end

**Comment by hirakiuc** [comment]
Thanks for your report.

It is exactly a typo and I'll fix it.
