### ISSUE TITLE
Loosen dependencies

### ISSUE THREAD

**Issue by lloydpick** [hirakiuc/tinybucket#55]
Hi,

The dependencies on activerecord and activemodel are hard set at 4.1.6, can this be loosened at all?

**Comment by dvbeato** [comment]
+1

**Comment by dvbeato** [comment]
Im trying to use tinybucket with rails 4.2.5 and Im getting the error `Bundler could not find compatible versions for gem "activemodel"`

**Comment by hirakiuc** [comment]
Oh, Sorry my late response.

PR #56 will merged soon and I'll release next version.
