### ISSUE TITLE
Support username and password

### ISSUE THREAD

**Issue by greggilbert** [hirakiuc/tinybucket#91]
In v2, it's possible to use your team name as a username and the API key as a password, and pass it along as a Basic-Auth header. It'd be great if that could be integrated here.

**Comment by hirakiuc** [comment]
Sorry, I've found your issue now. 😭 

I can't found such authentication method in [Bitbucket Cloud API documentation](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html).

Please show me the documentation link if you still want to support the auth method. 😄

**Comment by hirakiuc** [comment]
Please re-open this issue if you still want to use your request and find the document about your requested feature.
