### ISSUE TITLE
Trying to print repos from a user

### ISSUE THREAD

**Issue by jmdelatorre** [hirakiuc/tinybucket#92]
Hi ,

I'm trying to print the repos from a specific user by using

```
@bucket = Tinybucket.new
puts @bucket.user('user').repos.to_json

```

but im not getting any information in the json 

any ideas on what im doing worng? thanks

**Comment by hirakiuc** [comment]
Sorry, poor documentation. 😭 

I'll respond in a while.

**Comment by jmdelatorre** [comment]
hahaha dont worry, when you can :)

**Comment by hirakiuc** [comment]
You can enumerate user's repositories like this.

```ruby
bucket = Tinybucket.new
repos = bucket.user('myname').repos
# repos is an instance of User::Repos resource model.
# #<Tinybucket::Resource::User::Repos:0x007ff5b4253120 @user_name="myname", @args=[{}]>

# you can enumerate repository with repos, like this!
repos do |repo|
    # repo is an instance of Tinybucket::Model::Repository
    puts repo.name
end
```

Please check [yard document](http://www.rubydoc.info/github/hirakiuc/tinybucket/master/Tinybucket/Model/Repository) about attributes of the Tinybucket::Model::Repository. 👀 

---

Tinybucket has a policy that pluralized method returns `Resource model` which can enumerable the  Model, such like `user`, `repository`,  `pull request`, and so on.

So you can call enumerable methods, such like `each`,`find`, `select` to `Resource model`, like above example.

Please check [here](https://github.com/hirakiuc/tinybucket#pagination). 👀 

I hope that you enjoy tinybucket. 😄

**Comment by jmdelatorre** [comment]
Hi again!
Im getting an error and im not sure why..  `undefined method `repos'` 
for some reason, when enumerating the repository, its not recognising the repos instanced before..

any idea why?

**Comment by hirakiuc** [comment]
Did you use my sample code that I paste above?
The code works for me with my bitbucket account name. 😄 

But you failed, right? 

By the error message `undefined method repos`, I guess that you send `repos` message to an object which does not respond `repos` message.

So, I think that you should debug your code to figure out which object receive `repos` method.

**Comment by jmdelatorre** [comment]
Yup! I tried with the sample code and I tried fixing it, doing

```
      bucket = Tinybucket.new
      repos = bucket.user('hirakiuc').repos do |repo|
        puts repo.name
      end
```

and now im not getting an error but its not printing anything :( 

I also tried with my bitbucket account so im not sure whats wrong

**Comment by hirakiuc** [comment]
Oh, sorry.

You should send `each` message to `repos` to enumerate user's repositories, like this.

```
bucket = Tinybucket.new
bucket.user('hirakiuc').repos.each do |repo|
  puts repo.name
end
```

It would be work ... 🙏

**Comment by atchyut-re** [comment]
@hirakiuc Thanks for this Answer. In the same way can you please elaborate for retrieval of commits as well?

I had tried as you mentioned in the documentation.

```
repos = bucket.repos('myname')
#<Tinybucket::Client:0x000000090b69f0> 

 repos = bucket.repos('atchyut_re')
 #<Tinybucket::Resource::Repos:0x00000007c299b0 @owner="atchyut_re", @args=[{}]> 

commits = repo.commits
#<Tinybucket::Resource::Commits:0x000000090bcf58 @repo=#<Tinybucket::Model::Repository:0x00000007b3f3b0 @_loaded=false, @repo_owner="atchyut_re", @repo_slug="ruby">, @args=[{}]> 
```


and after getting these commits I wish to loop them and get each commit message to be printed. Can you please help me with this?

**Comment by hirakiuc** [comment]
I'll close this issue because you have no responses in two months.

Please reopen this if you have any questions.

Thanks!
