### ISSUE TITLE
OAuth2 support?

### ISSUE THREAD

**Issue by falexandrou** [hirakiuc/tinybucket#93]
Hello, 

Is OAuth2 supported by this gem? If so, how are we assigning client id, client secret and access_token ?

Thanks

**Comment by hirakiuc** [comment]
Thank you for your report (and #94)!

Currently, this gem does not support OAuth2 yet. 😭 

Because I just find that `Bitbucket REST API` supports `OAuth2`, by this issue. 😅 

Certainly, I think this gem should support OAuth2 in near feature. 👍

**Comment by hirakiuc** [comment]
I checked Bitbucket API document and found that require callback URI.

I've created this gem to use in some batch or some simple script.
So I wonder whether should this gem need to implement OAuth2 support or not.

Do you want to use this gem in OAuth2 protocol with user's grant?

**Comment by ezploydemo** [comment]
Hi @hirakiuc 

In my case i had to overload the middleware in order to support the OAuth2 Token Bearer, it would be nice if it had some kind of built in support. In my case i did:

```ruby
conn.authorization :Bearer, Tinybucket.config.access_token
```

**Comment by falexandrou** [comment]
Hi @hirakiuc 

In my case i had to overload the middleware in order to support the OAuth2 Token Bearer, it would be nice if it had some kind of built in support. In my case i did:

```ruby
conn.authorization :Bearer, Tinybucket.config.access_token
```

PS. Sorry, I replied from one of my test accounts 😄

**Comment by hirakiuc** [comment]
Sorry, late response. 😭 

Hmm, I see.

According to the [Bitbucket API document](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Refreshtokens), the OAuth2 access token will expire in one hour.

So I think that this gem should also support refreshing the access token with OAuth2 Authentication.

O.K, I'll try to implement this behavior in this yearend. 👍

**Comment by hirakiuc** [comment]
Hi, I've added OAuth2 access_token support by #106.

But #106 does not include refreshing access_token functionality, yet.

I'll add the feature in another issue.(#107)

So, this issue fixed in master branch (not yet released.)
