### ISSUE TITLE
403 error which getting commits from a private repo

### ISSUE THREAD

**Issue by atchyut-re** [hirakiuc/tinybucket#95]
I was trying to get the commit messages data from bitbucket of a private repository. For this I wrote a loop

```
commits.each do |commit|
    puts commit.message
end
```
In the rails console, after running that loop I stuck with an error:
`ERROR -- : Invalid response code:403
Tinybucket::Error::ServiceError:`

Well, then I tried to open the api url in the browser manually which gave me popup asking for user id, password. I further explored on this 403 FORBIDDEN error and found some answers saying

> Returned if the caller attempts to make a call or modify a resource for which the caller is not authorized. The request was a valid request, the caller's authentication credentials succeeded but those credentials do not grant the caller permission to access the resource.

Can someone please explain to me why I could be getting a 403 error when an API request originates from rails console, and also how to get my code authenticated before getting the data from bitbucket.

**Comment by hirakiuc** [comment]
Hi, thank you for using my gem! 😄 

When you retrieve your private repository data, you must use your OAuth 1.0 key and secret. 🔑  

(Sorry, current tinybucket does not support OAuth2 yet. 😢 )

[Please check here](https://github.com/hirakiuc/tinybucket#configure) about how to configure your OAuth key and secret. 📓 

And you can create your OAuth 1.0 key and secret on bitbucket.

Please Check this document  ➡️  [Step 1. Create an OAuth key and secret](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Step1.CreateanOAuthkeyandsecret).
