### ISSUE TITLE
Retrieving list of branches from a repository.

### ISSUE THREAD

**Issue by atchyut-re** [hirakiuc/tinybucket#97]
Hello @hirakiuc ,

I got requirement in my project to list out all branches from a repository and compare code among them.
I had went through our gem documentation and bitbucket api 2.0 documentation. What I found was they are listing all branches from this type of url:
 `https://api.bitbucket.org/2.0/repositories/#{@repository.owner_name}/#{@repository.name}/refs/branches`

But I had noticed in our gem you are using ``https://api.bitbucket.org/2.0/repositories/#{@repository.owner_name}/#{@repository.name}/branches_restrictions`

and there is no functionality for listing out branches. Well I tried to access my bitbucket api by following the way you had used in `connection.rb` file.

But the result was a `forbidden` error.
Can you please help me to access the api for get the url specified above for getting the branches list and compare files among them. (I had implemented this with github) or please help me how to use TinyBucket to get list of branches.

**Code I had written:**
```
attrs = {
          headers: {
            USER_AGENT: 'test client' # TODO: fix this !
          },
          ssl: { verify: false },
          url: 'https://api.bitbucket.org'
        }

oauth_secrets = {
          consumer_key:    Repository.last.key,
          consumer_secret: Repository.last.secret
        }
        conn = Faraday.new(attrs)
        conn.request :oauth, oauth_secrets
        conn.get("/2.0/repositories/#{Repository.last.owner_name}/#{Repository.last.name}/refs/branches")

```
Thanks in advance. :)

**Comment by hirakiuc** [comment]
Hi. ✋ 

> and there is no functionality for listing out branches

Yes. 

This gem has some lack of features because this gem does not follow latest `Bitbucket REST API` spec, just like `listing branches`, #93, and so on. 😭 

> Can you please help me to access the API for get the url specified above for getting the branches list and compare files among them. (I had implemented this with github) or please help me how to use TinyBucket to get list of branches.

If you want to write the code to listing branches, please check #94.
The PR will help you, I think. 😄 

And I'll try to update this gem to follow the latest `Bitbucket REST API` spec. 💪 

So this gem will have the feature to listing branches in the future. 🙏

**Comment by hirakiuc** [comment]
Please check #102 if you still have some issue. 😄 

NOTE: The listing branches feature will add by #102.
